const express = require("express");
const router = express.Router();
const reportController = require("../controllers/reportController");
const authMiddleware = require("../middleware/authMiddleware");

// All report routes should be protected
router.use(authMiddleware);

// POST /api/reports - Save a generated report to history
router.post("/", reportController.saveReport);

// GET /api/reports/:userId - Get all reports generated by a user
router.get("/:userId", reportController.getReportHistory);

// DELETE /api/reports/:id - Remove a report from history
router.delete("/:id", reportController.deleteReportHistory);

module.exports = router;
